### ISSUE TITLE
How to build fgt in Visual studio after generating bin through CMAKE?

### ISSUE THREAD

**Issue by zahidmak** [gadomski/fgt#40]
Hello,

Could you please help on how I can build fgt using Visual Studio after generating bin through CMAKE.

Which is project should I set as Start up project.

Thank you in advanced.

**Comment by gadomski** [comment]
Hi @zahidmak, here's the steps I use to build fgt on Windows:

1) Set up CMake to generate a Visual Studio solution (in my case, `Visual Studio 15 2017 Win64`) in a `build` subdirectory of the fgt repo. Click `Configure`, then `Generate`, ensuring that all errors are cleared up by setting variables (e.g. the Eigen location).
![image](https://user-images.githubusercontent.com/58314/27143449-a23e55d6-50eb-11e7-9fab-ff750bcc21b9.png)
2) Open the Visual Studio solution.
![image](https://user-images.githubusercontent.com/58314/27143539-ec360490-50eb-11e7-86ec-fec8211876ec.png)
3) Build the project (F7, or `ALL_BUILD`).

Let me know if that information is enough to get you rolling.

**Comment by gadomski** [comment]
Closing as no-response, feel free to re-open if these instructions don't help.
